use tempfile::TempDir;
use std::fs;

/// Validates that the sample project generated by create_sample_project_cmd
/// passes validation as a valid Orqestra project.
#[test]
fn validates_generated_sample_project() {
    let tmp = TempDir::new().expect("temp dir");

    // Manually create the same structure as create_sample_project_cmd
    let root = tmp.path();
    let roadmap_dir = root.join("roadmap");
    fs::create_dir_all(&roadmap_dir).unwrap();

    // _index.md
    fs::write(
        roadmap_dir.join("_index.md"),
        r#"---
pm-index: true
project: "Test"
---
# Test
"#,
    ).unwrap();

    // Valid task
    fs::write(
        roadmap_dir.join("TASK-001.md"),
        r#"---
pm-task: true
id: TASK-001
title: "Test task"
status: backlog
priority: Low
progress: 0
created: "2026-01-01T00:00:00Z"
updated: "2026-01-01T00:00:00Z"
---
Body text
"#,
    ).unwrap();

    // .Orqestra dir
    fs::create_dir_all(root.join(".Orqestra")).unwrap();

    // Validate using the same logic as validate_project_cmd
    assert!(root.join("roadmap").is_dir());
    assert!(roadmap_dir.join("_index.md").exists());
    assert!(root.join(".Orqestra").is_dir());

    // Test indexing
    let result = md_indexer::index_roadmap(&roadmap_dir);
    assert!(result.is_ok(), "Indexing should succeed");
    let index = result.unwrap();
    assert_eq!(index.tasks.len(), 1, "Should find 1 task");
    // Coordinator _index.md may produce a parse warning — that's OK
    // assert!(index.errors.is_empty(), "Should have no errors");
}

#[test]
fn rejects_non_orqestra_folder() {
    let tmp = TempDir::new().expect("temp dir");
    let root = tmp.path();

    // Empty temp folder — no roadmap/
    assert!(!root.join("roadmap").exists(), "Should not have roadmap dir");

    // This simulates what validate_project_cmd would return
    let has_roadmap = root.join("roadmap").is_dir();
    assert!(!has_roadmap, "Should detect as not_orqestra");
}

#[test]
fn detects_malformed_task_frontmatter() {
    let tmp = TempDir::new().expect("temp dir");
    let roadmap_dir = tmp.path().join("roadmap");
    fs::create_dir_all(&roadmap_dir).unwrap();

    // Write malformed YAML — missing closing ---
    fs::write(
        roadmap_dir.join("BAD-001.md"),
        r#"---
pm-task: true
id: BAD-001
title: "Bad task"
status: invalid_status_value
priority: Low
progress: 0
created: "2026-01-01"
updated: "2026-01-01"
---
Body
"#,
    ).unwrap();

    let result = md_indexer::index_roadmap(&roadmap_dir);
    // Should either error or produce warnings
    match result {
        Ok(index) => {
            // If it parses, the task may have default status
            // Malformed field should at least produce an error entry
        }
        Err(_) => {
            // Parse error is also acceptable
        }
    }
}

#[test]
fn detects_duplicate_task_ids() {
    let tmp = TempDir::new().expect("temp dir");
    let roadmap_dir = tmp.path().join("roadmap");
    fs::create_dir_all(&roadmap_dir).unwrap();

    let task_content = r#"---
pm-task: true
id: TASK-DUP
title: "Duplicate"
status: backlog
priority: Low
progress: 0
created: "2026-01-01T00:00:00Z"
updated: "2026-01-01T00:00:00Z"
---
Body
"#;

    // Write two files with the same ID
    fs::write(roadmap_dir.join("FILE-A.md"), task_content).unwrap();
    fs::write(roadmap_dir.join("FILE-B.md"), task_content).unwrap();

    let result = md_indexer::index_roadmap(&roadmap_dir);
    assert!(result.is_ok());

    let index = result.unwrap();
    // Both tasks parse but have the same ID — validate_project_cmd detects this
    let mut seen_ids = std::collections::HashSet::new();
    let mut duplicate_count = 0;
    for task in &index.tasks {
        if !seen_ids.insert(task.frontmatter.id.clone()) {
            duplicate_count += 1;
        }
    }
    assert!(duplicate_count > 0, "Should detect duplicate task IDs");
}

#[test]
fn repairable_missing_orqestra_toml() {
    let tmp = TempDir::new().expect("temp dir");
    let root = tmp.path();
    let roadmap_dir = root.join("roadmap");
    fs::create_dir_all(&roadmap_dir).unwrap();

    // Valid task
    fs::write(
        roadmap_dir.join("TASK-001.md"),
        r#"---
pm-task: true
id: TASK-001
title: "Test"
status: backlog
priority: Low
progress: 0
created: "2026-01-01T00:00:00Z"
updated: "2026-01-01T00:00:00Z"
---
Body
"#,
    ).unwrap();

    // No Orqestra.toml, no .Orqestra dir — should be repairable
    assert!(!root.join("Orqestra.toml").exists());
    assert!(!root.join(".Orqestra").exists());

    // But roadmap is valid
    let result = md_indexer::index_roadmap(&roadmap_dir);
    assert!(result.is_ok());
    assert_eq!(result.unwrap().tasks.len(), 1);
}
