/**
 * Dashboard data types and mock data.
 * In production, fetched from a static JSON endpoint generated by CI.
 */
export type TaskStatus = 'todo' | 'in-progress' | 'review' | 'done' | 'blocked';

export type Task = {
  id: string;
  title: string;
  status: TaskStatus;
  priority: 'low' | 'medium' | 'high' | 'critical';
  assignee?: string;
  sprint?: string;
  epic?: string;
  start_date?: string;
  end_date?: string;
  depends_on?: string[];
  description?: string;
};

// Mock data matching the actual roadmap/ files
export const TASKS: Task[] = [
  {
    id: 'TASK-2026-038',
    title: 'Implement authentication middleware',
    status: 'in-progress',
    priority: 'high',
    assignee: 'alice',
    sprint: 'Sprint 14',
    epic: 'epic-security',
    start_date: '2026-06-01',
    end_date: '2026-06-07',
    depends_on: [],
    description: 'Build JWT-based authentication middleware for the API layer.',
  },
  {
    id: 'TASK-2026-040',
    title: 'Add caching layer for API responses',
    status: 'todo',
    priority: 'medium',
    assignee: 'bob',
    sprint: 'Sprint 14',
    epic: 'epic-performance',
    start_date: '2026-06-08',
    end_date: '2026-06-14',
    depends_on: ['TASK-2026-038'],
    description: 'Implement Redis-based caching with TTL management.',
  },
  {
    id: 'TASK-2026-042',
    title: 'Rate limiting middleware',
    status: 'done',
    priority: 'critical',
    assignee: 'alice',
    sprint: 'Sprint 14',
    epic: 'epic-security',
    start_date: '2026-06-01',
    end_date: '2026-06-05',
    depends_on: ['TASK-2026-038'],
    description: 'Token bucket rate limiter with configurable limits per endpoint.',
  },
  {
    id: 'TASK-2026-045',
    title: 'Database migration system',
    status: 'review',
    priority: 'high',
    assignee: 'charlie',
    sprint: 'Sprint 15',
    epic: 'epic-infra',
    start_date: '2026-06-15',
    end_date: '2026-06-21',
    depends_on: [],
    description: 'Versioned database migrations with rollback support.',
  },
  {
    id: 'TASK-2026-050',
    title: 'Rate limiting UI dashboard',
    status: 'blocked',
    priority: 'medium',
    assignee: 'bob',
    sprint: 'Sprint 15',
    epic: 'epic-security',
    start_date: '2026-06-22',
    end_date: '2026-06-28',
    depends_on: ['TASK-2026-042', 'TASK-2026-040'],
    description: 'Real-time rate limiting metrics and configuration UI.',
  },
];

export const SPRINTS = [
  { id: 'Sprint 14', title: 'Auth & Caching', start: '2026-06-01', end: '2026-06-14', status: 'active' },
  { id: 'Sprint 15', title: 'Infrastructure', start: '2026-06-15', end: '2026-06-28', status: 'upcoming' },
];

export const STATUS_COLORS: Record<TaskStatus, string> = {
  'todo': '#6b7280',
  'in-progress': '#3b82f6',
  'review': '#f59e0b',
  'done': '#22c55e',
  'blocked': '#ef4444',
};

export const PRIORITY_COLORS: Record<string, string> = {
  'low': '#6b7280',
  'medium': '#3b82f6',
  'high': '#f59e0b',
  'critical': '#ef4444',
};
