/**
 * Orqestra Public Dashboard
 *
 * Read-only Gantt + Kanban views rendered from real roadmap/ data.
 * Data is loaded from orqestra-roadmap.json generated by the CLI.
 */
import React, { useState, useEffect } from 'react';
import { PublicGantt } from './components/PublicGantt';
import { PublicKanban } from './components/PublicKanban';
import { TokenGate } from './components/TokenGate';
import { SourceMetadata } from './components/SourceMetadata';
import {
  fetchRoadmapData,
  STATUS_COLORS,
  type RoadmapData,
  type Task,
  type Sprint,
} from './lib/data';

type View = 'gantt' | 'kanban' | 'table';
type LoadState = 'loading' | 'loaded' | 'error';

export function App() {
  const [view, setView] = useState<View>('kanban');
  const [authScope, setAuthScope] = useState<string | null>(null);
  const [data, setData] = useState<RoadmapData | null>(null);
  const [loadState, setLoadState] = useState<LoadState>('loading');

  useEffect(() => {
    fetchRoadmapData().then(d => {
      if (d && d.tasks.length > 0) {
        setData(d);
        setLoadState('loaded');
      } else {
        setLoadState('error');
      }
    }).catch(() => setLoadState('error'));
  }, []);

  if (loadState === 'loading') {
    return (
      <div style={{ maxWidth: 1400, margin: '0 auto', padding: 24, textAlign: 'center' }}>
        <h1 style={{ fontSize: 24, fontWeight: 700 }}>Orqestra Dashboard</h1>
        <p style={{ color: '#94a3b8', marginTop: 16 }}>Loading roadmap data...</p>
      </div>
    );
  }

  if (loadState === 'error' || !data) {
    return (
      <div style={{ maxWidth: 1400, margin: '0 auto', padding: 24, textAlign: 'center' }}>
        <h1 style={{ fontSize: 24, fontWeight: 700 }}>Orqestra Dashboard</h1>
        <p style={{ color: '#ef4444', marginTop: 16 }}>
          Failed to load roadmap data. The dashboard requires orqestra-roadmap.json to be generated first.
        </p>
        <p style={{ color: '#94a3b8', fontSize: 13, marginTop: 8 }}>
          Run: <code style={{ backgroundColor: '#1e293b', padding: '2px 6px', borderRadius: 4 }}>cargo run --bin orqestra -- export --project-root . --format=json --out apps/dashboard/public/orqestra-roadmap.json</code>
        </p>
      </div>
    );
  }

  const tasks = data.tasks;
  const summary = data.summary;

  const statusCounts = {
    total: summary.total_tasks,
    done: summary.done,
    inProgress: summary.in_progress,
    blocked: summary.blocked,
    backlog: summary.backlog,
    ready: summary.ready,
  };

  return (
    <div style={{ maxWidth: 1400, margin: '0 auto', padding: 24 }}>
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
          <div>
            <h1 style={{ margin: 0, fontSize: 24, fontWeight: 700 }}>Orqestra Dashboard</h1>
            <span style={{ color: '#64748b', fontSize: 13 }}>
              Public project tracker · {data.source.repo}@{data.source.commit}
            </span>
          </div>
          {authScope && (
            <div style={{
              padding: '4px 12px', borderRadius: 6,
              backgroundColor: '#22c55e33', color: '#22c55e', fontSize: 13, fontWeight: 600,
            }}>
              Private View
            </div>
          )}
        </div>

        {/* Stats bar */}
        <div style={{ display: 'flex', gap: 16, marginBottom: 16, flexWrap: 'wrap' }}>
          {[
            { label: 'Total Tasks', value: statusCounts.total, color: '#e2e8f0' },
            { label: 'Done', value: statusCounts.done, color: '#22c55e' },
            { label: 'In Progress', value: statusCounts.inProgress, color: '#3b82f6' },
            { label: 'Backlog', value: statusCounts.backlog, color: '#6b7280' },
            { label: 'Ready', value: statusCounts.ready, color: '#8b5cf6' },
          ].map(s => (
            <div key={s.label} style={{
              padding: '8px 16px', backgroundColor: '#1e293b', borderRadius: 8,
              minWidth: 100,
            }}>
              <div style={{ fontSize: 20, fontWeight: 700, color: s.color }}>{s.value}</div>
              <div style={{ fontSize: 11, color: '#64748b' }}>{s.label}</div>
            </div>
          ))}
        </div>

        {/* Source metadata */}
        <SourceMetadata
          source={data.source}
          generatedAt={data.generated_at}
          taskCount={data.summary.total_tasks}
          coherence={data.coherence}
        />

        {/* Token Gate */}
        <TokenGate onAuth={(_, scope) => setAuthScope(scope)} />

        {/* View switcher */}
        <div style={{ display: 'flex', gap: 4, marginBottom: 16 }}>
          {(['kanban', 'gantt', 'table'] as View[]).map(v => (
            <button
              key={v}
              onClick={() => setView(v)}
              style={{
                padding: '6px 16px', border: 'none', borderRadius: 6,
                cursor: 'pointer', fontWeight: 600, fontSize: 13,
                backgroundColor: view === v ? '#3b82f6' : '#1e293b',
                color: view === v ? '#fff' : '#94a3b8',
              }}
            >
              {v.charAt(0).toUpperCase() + v.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* Content */}
      {view === 'gantt' && <PublicGantt tasks={tasks} />}
      {view === 'kanban' && <PublicKanban tasks={tasks} />}
      {view === 'table' && (
        <div style={{ overflowX: 'auto' }}>
          <table style={{
            width: '100%', borderCollapse: 'collapse',
            backgroundColor: '#0f172a', borderRadius: 8, overflow: 'hidden',
          }}>
            <thead>
              <tr style={{ backgroundColor: '#1e293b' }}>
                {['ID', 'Title', 'Status', 'Priority', 'Assignee', 'Sprint', 'Dates'].map(h => (
                  <th key={h} style={{
                    padding: '10px 12px', textAlign: 'left', fontSize: 12,
                    fontWeight: 600, color: '#94a3b8', borderBottom: '1px solid #334155',
                  }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {tasks.map(t => (
                <tr key={t.id} style={{ borderBottom: '1px solid #1e293b' }}>
                  <td style={{ padding: '8px 12px', fontFamily: 'monospace', fontSize: 13 }}>{t.id}</td>
                  <td style={{ padding: '8px 12px', fontSize: 13 }}>{t.title}</td>
                  <td style={{ padding: '8px 12px', fontSize: 13, textTransform: 'capitalize' }}>{t.status}</td>
                  <td style={{ padding: '8px 12px', fontSize: 13 }}>{t.priority}</td>
                  <td style={{ padding: '8px 12px', fontSize: 13 }}>{t.assignee || '—'}</td>
                  <td style={{ padding: '8px 12px', fontSize: 13 }}>{t.sprint || '—'}</td>
                  <td style={{ padding: '8px 12px', fontSize: 12, color: '#94a3b8' }}>
                    {t.start_date && t.due_date ? `${t.start_date} → ${t.due_date}` : '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Footer */}
      <div style={{ marginTop: 24, padding: '12px 0', borderTop: '1px solid #1e293b', fontSize: 12, color: '#64748b' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
          <span>Generated: {new Date(data.generated_at).toLocaleString()}</span>
          <span>{data.source.repo}@{data.source.branch} ({data.source.commit})</span>
        </div>
        {data.release && (
          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 4 }}>
            <span>Release: v{data.release.version}</span>
            <span title={data.release.source_commit}>Source: {data.release.source_commit.slice(0, 12)}...</span>
          </div>
        )}
      </div>
    </div>
  );
}
